services:
  steam:
    ipc: host
    build: .
    restart: unless-stopped
    network_mode: host  # Disabled to use port mappings for Sunshine
    privileged: true

    environment:
      - PUID=1000
      - PGID=1000
      - RENDER_GID=989
      - TZ=America/Denver

      - WLR_RENDERER=vulkan
      - AMD_VULKAN_ICD=RADV
      - WLR_DRM_NO_MODIFIERS=1
      - WLR_BACKENDS=headless
      - WLR_LIBINPUT_NO_DEVICES=1
      - WLR_RENDERER=pixman
      - XDG_CURRENT_DESKTOP=sway

    # entrypoint: []
    volumes:
      - ./data/.config:/home/retro/.config

      # - ${HOME}/.local/share/Steam/steamapps:/mnt/local/SteamLibrary/steamapps
      - ${HOME}/.local/share/Steam:/home/retro/.local/share/Steam
      - /mnt/ntfs/SteamLibrary:/mnt/ntfs/SteamLibrary

      # 3. SYSTEM
      - /run/udev:/run/udev:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    devices:
      - /dev/dri:/dev/dri
      - /dev/uinput:/dev/uinput
      - /dev/input:/dev/input  # Added for Sunshine input handling

    ports:
      - "5900:5900"

    command:  gamescope --backend headless -e -W 1280 -H 800 -r 60 -- steam --gamepadui
