services:
  steam:
    container_name: steam
    ipc: host
    build:
      context: .
      target: amd
    network_mode: host
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    cap_add:
      - SYS_NICE      # Required for Gamescope priority/performance
      - SYS_PTRACE    # Required for Proton/Wine anti-cheat and process handling

    environment:
      - WLR_DRM_NO_MODIFIERS=1
      - WLR_BACKENDS=headless
      - WLR_RENDERER=pixman

    volumes:
      - steam_home:/home/retro
      - /run/udev:/run/udev:ro
      - /dev/input:/dev/input
      - ./config:/app/config

    devices:
      - /dev/fuse
      - /dev/dri:/dev/dri
      - /dev/uinput:/dev/uinput
    device_cgroup_rules:
      - 'c 13:* rmw'       # Input devices (joysticks, gamepads)
      - 'c 226:* rmw'      # DRI/GPU devices
      - 'c 10:223 rmw'     # uinput (virtual controller creation)

    # command: steam -steamos3 -gamepadui
    command: /app/launch.sh steam -steamos3 -gamepadui

  res:
    restart: unless-stopped
    build: ./res
    container_name: res
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock

  debug:
    extends: steam
    container_name: debug
    profiles:
      - debug
    build:
      context: .
      target: debug
    volumes:
      - ./sway_config:/home/retro/.config/sway/config:ro
    command: sway

volumes:
  steam_home:
